-- MySQL Script generated by MySQL Workbench
-- Sun Feb  3 02:58:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema salabv2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salabv2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salabv2` DEFAULT CHARACTER SET latin1 ;
USE `salabv2` ;

-- -----------------------------------------------------
-- Table `salabv2`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Carrera` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `nombre_ca` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `noControl` VARCHAR(45) NULL,
  `nombre_al` VARCHAR(45) NULL,
  `aPaterno_al` VARCHAR(45) NULL,
  `aMaterno_al` VARCHAR(45) NULL,
  `idCarrera` INT NOT NULL,
  PRIMARY KEY (`idAlumno`, `idCarrera`),
  INDEX `fk_Alumnos_Carrera_idx` (`idCarrera` ASC),
  CONSTRAINT `fk_Alumnos_Carrera`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `salabv2`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`Estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Estatus` (
  `idEstatus` INT NOT NULL DEFAULT 1,
  `nombre_estatus` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Profesor` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `nombre_pr` VARCHAR(45) NULL,
  `aPaterno_pr` VARCHAR(45) NULL,
  `aMaterno_pr` VARCHAR(45) NULL,
  `idEstatus` INT NOT NULL DEFAULT 3,
  PRIMARY KEY (`idProfesor`, `idEstatus`),
  INDEX `fk_Profesor_Estatus1_idx` (`idEstatus` ASC),
  CONSTRAINT `fk_Profesor_Estatus1`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `salabv2`.`Estatus` (`idEstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Asignatura` (
  `idAsignatura` INT NOT NULL AUTO_INCREMENT,
  `nombre_as` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `idCarrera` INT NOT NULL,
  `idProfesor` INT NOT NULL,
  `idEstatus` INT NOT NULL DEFAULT 3,
  PRIMARY KEY (`idAsignatura`, `idCarrera`, `idProfesor`, `idEstatus`),
  INDEX `fk_Asignatura_Carrera1_idx` (`idCarrera` ASC),
  INDEX `fk_Asignatura_Profesor1_idx` (`idProfesor` ASC),
  INDEX `fk_Asignatura_Estatus1_idx` (`idEstatus` ASC),
  CONSTRAINT `fk_Asignatura_Carrera1`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `salabv2`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_Profesor1`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `salabv2`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_Estatus1`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `salabv2`.`Estatus` (`idEstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Aula` (
  `idAula` INT NOT NULL AUTO_INCREMENT,
  `nombre_au` VARCHAR(45) NULL,
  PRIMARY KEY (`idAula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`Computadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Computadora` (
  `idComputadora` INT NOT NULL AUTO_INCREMENT,
  `fabricante` VARCHAR(45) NULL,
  `procesador` VARCHAR(45) NULL,
  `memoriaInstalada` VARCHAR(45) NULL,
  `discoDuro` VARCHAR(45) NULL,
  `soVersion` VARCHAR(45) NULL,
  `tipoSistema` VARCHAR(45) NULL,
  `numeroSerie` VARCHAR(45) NULL,
  `fechaAlta` DATETIME(6) NULL,
  `fechaIngreso` DATETIME(6) NULL,
  `comentarios` VARCHAR(255) NULL,
  `idAula` INT NOT NULL DEFAULT 1,
  `idEstatus` INT NOT NULL DEFAULT 3,
  `control` INT NULL DEFAULT 0,
  `comp_ip` VARCHAR(15) NULL DEFAULT '0.0.0.0',
  `comp_numero` INT NULL DEFAULT 0,
  PRIMARY KEY (`idComputadora`, `idAula`, `idEstatus`),
  INDEX `fk_Computadora_Estatus1_idx` (`idEstatus` ASC),
  INDEX `fk_Computadora_Aula1_idx` (`idAula` ASC),
  INDEX `fk_Computadora_comp_numero1_idx` (`comp_numero` ASC),
  CONSTRAINT `fk_Computadora_Estatus1`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `salabv2`.`Estatus` (`idEstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computadora_Aula1`
    FOREIGN KEY (`idAula`)
    REFERENCES `salabv2`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`TipoDispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`TipoDispositivo` (
  `idTipoDispositivo` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipdis` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoDispositivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`Dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Dispositivo` (
  `idDispositivo` INT NOT NULL AUTO_INCREMENT,
  `fabricante` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `numeroSerie` VARCHAR(45) NULL,
  `idTipoDispositivo` INT NOT NULL,
  `fechaAlta` DATETIME(6) NULL,
  `fechaIngreso` DATETIME(6) NULL,
  `comentarios` VARCHAR(255) NULL,
  `idAula` INT NOT NULL,
  `idEstatus` INT NOT NULL DEFAULT 3,
  PRIMARY KEY (`idDispositivo`, `idTipoDispositivo`, `idAula`, `idEstatus`),
  INDEX `fk_Monitor_Estatus1_idx` (`idEstatus` ASC),
  INDEX `fk_Inventario_Tipo_Equipo1_idx` (`idTipoDispositivo` ASC),
  INDEX `fk_Dispositivo_Aula1_idx` (`idAula` ASC),
  CONSTRAINT `fk_Monitor_Estatus1`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `salabv2`.`Estatus` (`idEstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Tipo_Equipo1`
    FOREIGN KEY (`idTipoDispositivo`)
    REFERENCES `salabv2`.`TipoDispositivo` (`idTipoDispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dispositivo_Aula1`
    FOREIGN KEY (`idAula`)
    REFERENCES `salabv2`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`TipoUsuario` (
  `idTipoUsuario` INT NOT NULL DEFAULT 3,
  `nombre_tipusr` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usr` VARCHAR(45) NOT NULL,
  `aPaterno_usr` VARCHAR(45) NULL,
  `aMaterno_usr` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `fechaCreacion` TIMESTAMP(6) NULL,
  `idTipoUsuario` INT NOT NULL DEFAULT 3,
  `idEstatus` INT NULL DEFAULT 1,
  PRIMARY KEY (`idUsuario`, `idTipoUsuario`),
  INDEX `fk_Usuario_TipoUsuario1_idx` (`idTipoUsuario` ASC),
  CONSTRAINT `fk_Usuario_TipoUsuario1`
    FOREIGN KEY (`idTipoUsuario`)
    REFERENCES `salabv2`.`TipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `horaInicio` TIME(6) NULL,
  `horaFin` TIME(6) NULL,
  `dia` VARCHAR(45) NULL,
  `idAula` INT NOT NULL,
  `idAsignatura` INT NOT NULL,
  `idCarrera` INT NOT NULL,
  `idProfesor` INT NOT NULL,
  `idEstatus` INT NOT NULL DEFAULT 3,
  PRIMARY KEY (`idHorario`, `idAula`, `idEstatus`),
  INDEX `fk_Horario_Aula1_idx` (`idAula` ASC),
  INDEX `fk_Horario_Asignatura1_idx` (`idAsignatura` ASC, `idCarrera` ASC, `idProfesor` ASC),
  INDEX `fk_Horario_Estatus1_idx` (`idEstatus` ASC),
  CONSTRAINT `fk_Horario_Aula1`
    FOREIGN KEY (`idAula`)
    REFERENCES `salabv2`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_Asignatura1`
    FOREIGN KEY (`idAsignatura` , `idCarrera` , `idProfesor`)
    REFERENCES `salabv2`.`Asignatura` (`idAsignatura` , `idCarrera` , `idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_Estatus1`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `salabv2`.`Estatus` (`idEstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`Reparacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Reparacion` (
  `idReparacion` INT NOT NULL AUTO_INCREMENT,
  `diagnostico` VARCHAR(45) NULL,
  `fechaInicio` DATETIME(6) NULL,
  `fechaFin` DATETIME(6) NULL,
  `idComputadora` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idEstatus` INT NOT NULL,
  PRIMARY KEY (`idReparacion`, `idUsuario`, `idEstatus`),
  INDEX `fk_Reparacion_Computadora1_idx` (`idComputadora` ASC),
  INDEX `fk_Reparacion_Estatus1_idx` (`idEstatus` ASC),
  INDEX `fk_Reparacion_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Reparacion_Computadora1`
    FOREIGN KEY (`idComputadora`)
    REFERENCES `salabv2`.`Computadora` (`idComputadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reparacion_Estatus1`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `salabv2`.`Estatus` (`idEstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reparacion_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `salabv2`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`ControlLab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`ControlLab` (
  `idControlLab` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` TIMESTAMP(6) NULL,
  `fechaFin` DATETIME(6) NULL,
  `noControl` VARCHAR(45) NULL,
  `idEstatus` INT NOT NULL,
  `control` INT NULL,
  `comp_numero` INT NULL,
  PRIMARY KEY (`idControlLab`, `idEstatus`),
  INDEX `fk_ControlLab_Estatus1_idx` (`idEstatus` ASC),
  INDEX `fk_ControlLab_comp_numero1_idx` (`comp_numero` ASC),
  CONSTRAINT `fk_ControlLab_Estatus1`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `salabv2`.`Estatus` (`idEstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ControlLab_comp_numero1`
    FOREIGN KEY (`comp_numero`)
    REFERENCES `salabv2`.`Computadora` (`comp_numero`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`Incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`Incidencia` (
  `idIncidencia` INT NOT NULL AUTO_INCREMENT,
  `asunto` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `comentario` VARCHAR(255) NULL,
  `fechaAlta` DATETIME(6) NULL,
  `fechaModificacion` DATETIME(6) NULL,
  `categoria` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  `idAula` INT NOT NULL,
  `idEstatus` INT NOT NULL DEFAULT 5,
  PRIMARY KEY (`idIncidencia`, `idUsuario`, `idEstatus`),
  INDEX `fk_Incidencias_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Incidencias_Estatus1_idx` (`idEstatus` ASC),
  INDEX `fk_Incidencia_Aula1_idx` (`idAula` ASC),
  CONSTRAINT `fk_Incidencias_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `salabv2`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidencias_Estatus1`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `salabv2`.`Estatus` (`idEstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidencia_Aula1`
    FOREIGN KEY (`idAula`)
    REFERENCES `salabv2`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salabv2`.`password_reset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salabv2`.`password_reset` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `selector` CHAR(16) NULL,
  `token` CHAR(64) NULL,
  `expires` BIGINT(20) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `salabv2`.`Carrera`
-- -----------------------------------------------------
START TRANSACTION;
USE `salabv2`;
INSERT INTO `salabv2`.`Carrera` (`idCarrera`, `nombre_ca`) VALUES (1, 'INGENIERIA EN SISTEMAS COMPUTACIONALES');
INSERT INTO `salabv2`.`Carrera` (`idCarrera`, `nombre_ca`) VALUES (2, 'INGENIERIA EN ADMINISTRACION');
INSERT INTO `salabv2`.`Carrera` (`idCarrera`, `nombre_ca`) VALUES (3, 'INGENIERIA EN GESTION EMPRESARIAL');
INSERT INTO `salabv2`.`Carrera` (`idCarrera`, `nombre_ca`) VALUES (4, 'INGENIERIA INFORMATICA');
INSERT INTO `salabv2`.`Carrera` (`idCarrera`, `nombre_ca`) VALUES (5, 'INGENIERIA CIVIL');
INSERT INTO `salabv2`.`Carrera` (`idCarrera`, `nombre_ca`) VALUES (6, 'INGENIERIA MECATRONICA');
INSERT INTO `salabv2`.`Carrera` (`idCarrera`, `nombre_ca`) VALUES (7, 'INGENIERIA ELECTROMECANICA');
INSERT INTO `salabv2`.`Carrera` (`idCarrera`, `nombre_ca`) VALUES (8, 'LICENCIATURA EN ADMINISTRACION');
INSERT INTO `salabv2`.`Carrera` (`idCarrera`, `nombre_ca`) VALUES (9, 'CONTADOR PUBLICO');

COMMIT;


-- -----------------------------------------------------
-- Data for table `salabv2`.`Estatus`
-- -----------------------------------------------------
START TRANSACTION;
USE `salabv2`;
INSERT INTO `salabv2`.`Estatus` (`idEstatus`, `nombre_estatus`) VALUES (1, 'ACTIVO');
INSERT INTO `salabv2`.`Estatus` (`idEstatus`, `nombre_estatus`) VALUES (2, 'INACTIVO');
INSERT INTO `salabv2`.`Estatus` (`idEstatus`, `nombre_estatus`) VALUES (3, 'ALTA');
INSERT INTO `salabv2`.`Estatus` (`idEstatus`, `nombre_estatus`) VALUES (4, 'BAJA');
INSERT INTO `salabv2`.`Estatus` (`idEstatus`, `nombre_estatus`) VALUES (5, 'EN PROCESO');
INSERT INTO `salabv2`.`Estatus` (`idEstatus`, `nombre_estatus`) VALUES (6, 'FINALIZADO');
INSERT INTO `salabv2`.`Estatus` (`idEstatus`, `nombre_estatus`) VALUES (7, 'SEGUIMIENTO');

COMMIT;


-- -----------------------------------------------------
-- Data for table `salabv2`.`Aula`
-- -----------------------------------------------------
START TRANSACTION;
USE `salabv2`;
INSERT INTO `salabv2`.`Aula` (`idAula`, `nombre_au`) VALUES (1, 'AULA 0');
INSERT INTO `salabv2`.`Aula` (`idAula`, `nombre_au`) VALUES (2, 'AULA 1');
INSERT INTO `salabv2`.`Aula` (`idAula`, `nombre_au`) VALUES (3, 'AULA 2');
INSERT INTO `salabv2`.`Aula` (`idAula`, `nombre_au`) VALUES (4, 'AULA 3');
INSERT INTO `salabv2`.`Aula` (`idAula`, `nombre_au`) VALUES (5, 'CONFERENCIAS');
INSERT INTO `salabv2`.`Aula` (`idAula`, `nombre_au`) VALUES (6, 'CISCO');
INSERT INTO `salabv2`.`Aula` (`idAula`, `nombre_au`) VALUES (7, 'UNIX');
INSERT INTO `salabv2`.`Aula` (`idAula`, `nombre_au`) VALUES (8, 'MICROPROCESADORES');
INSERT INTO `salabv2`.`Aula` (`idAula`, `nombre_au`) VALUES (9, 'OFICINA LAB');

COMMIT;


-- -----------------------------------------------------
-- Data for table `salabv2`.`TipoDispositivo`
-- -----------------------------------------------------
START TRANSACTION;
USE `salabv2`;
INSERT INTO `salabv2`.`TipoDispositivo` (`idTipoDispositivo`, `nombre_tipdis`) VALUES (1, 'MOUSE');
INSERT INTO `salabv2`.`TipoDispositivo` (`idTipoDispositivo`, `nombre_tipdis`) VALUES (2, 'TECLADO');
INSERT INTO `salabv2`.`TipoDispositivo` (`idTipoDispositivo`, `nombre_tipdis`) VALUES (3, 'MONITOR');
INSERT INTO `salabv2`.`TipoDispositivo` (`idTipoDispositivo`, `nombre_tipdis`) VALUES (4, 'CAÑON');

COMMIT;


-- -----------------------------------------------------
-- Data for table `salabv2`.`TipoUsuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `salabv2`;
INSERT INTO `salabv2`.`TipoUsuario` (`idTipoUsuario`, `nombre_tipusr`) VALUES (1, 'ADMIN');
INSERT INTO `salabv2`.`TipoUsuario` (`idTipoUsuario`, `nombre_tipusr`) VALUES (2, 'TIPO2');
INSERT INTO `salabv2`.`TipoUsuario` (`idTipoUsuario`, `nombre_tipusr`) VALUES (3, 'TIPO3');

COMMIT;


-- -----------------------------------------------------
-- Data for table `salabv2`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `salabv2`;
INSERT INTO `salabv2`.`Usuario` (`idUsuario`, `nombre_usr`, `aPaterno_usr`, `aMaterno_usr`, `email`, `username`, `password`, `telefono`, `fechaCreacion`, `idTipoUsuario`, `idEstatus`) VALUES (1, 'EDUARDO', 'CAUICH', 'HERRERA', 'lalo_lego@hotmail.com', 'xsirlalo', '21232f297a57a5a743894a0e4a801fc3', '9982366146', '2018-05-31 11:48:02.000000', 1, 1);

COMMIT;

